apiVersion: v1
kind: PersistentVolume
metadata:
  name: myebsvol
  namespace: react-django-ns
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  awsElasticBlockStore:
    volumeID: vol-0a099a3d142f55e58
    fsType: ext4
