apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
    - name: ctr1
      image: nginx:1.14.2
      ports:
        - containerPort: 80
      env:
        - name: MYENV
          valueFrom:
            configMapKeyRef:
              name: config12
              key: first_name
