apiVersion: v1
kind: Pod
metadata:
  name: config-pod
spec:
  containers:
    - name: container1
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - name: config-vol
          mountPath: "/config"
  volumes:
    - name: config-vol
      configMap:
        name:  game-demo
        items:
          - key: config.yaml
            path: config.yaml
